theme: "just-the-docs"
color_scheme: dark
heading_anchors: true

defaults:
  -
    scope:
      path: "index.md"
    values:
      layout: "home"
  -
    scope:
      path: "**/*.md"
    values:
      layout: "page"

source: "krate"
